//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8beatMap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NotetypeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotetypeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_8beatMap.NotetypeNames", typeof(NotetypeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlickLeft.
        /// </summary>
        internal static string FlickLeft {
            get {
                return ResourceManager.GetString("FlickLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlickRight.
        /// </summary>
        internal static string FlickRight {
            get {
                return ResourceManager.GetString("FlickRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GbsClock.
        /// </summary>
        internal static string GbsClock {
            get {
                return ResourceManager.GetString("GbsClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GbsFlick.
        /// </summary>
        internal static string GbsFlick {
            get {
                return ResourceManager.GetString("GbsFlick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GbsSimulClock.
        /// </summary>
        internal static string GbsSimulClock {
            get {
                return ResourceManager.GetString("GbsSimulClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GbsSimulFlick.
        /// </summary>
        internal static string GbsSimulFlick {
            get {
                return ResourceManager.GetString("GbsSimulFlick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold.
        /// </summary>
        internal static string Hold {
            get {
                return ResourceManager.GetString("Hold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoldEndFlickLeft.
        /// </summary>
        internal static string HoldEndFlickLeft {
            get {
                return ResourceManager.GetString("HoldEndFlickLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoldEndFlickRight.
        /// </summary>
        internal static string HoldEndFlickRight {
            get {
                return ResourceManager.GetString("HoldEndFlickRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulHoldRelease.
        /// </summary>
        internal static string SimulHoldRelease {
            get {
                return ResourceManager.GetString("SimulHoldRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulHoldStart.
        /// </summary>
        internal static string SimulHoldStart {
            get {
                return ResourceManager.GetString("SimulHoldStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulTap.
        /// </summary>
        internal static string SimulTap {
            get {
                return ResourceManager.GetString("SimulTap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwipeChangeDirL2R.
        /// </summary>
        internal static string SwipeChangeDirL2R {
            get {
                return ResourceManager.GetString("SwipeChangeDirL2R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwipeChangeDirR2L.
        /// </summary>
        internal static string SwipeChangeDirR2L {
            get {
                return ResourceManager.GetString("SwipeChangeDirR2L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwipeLeftMid.
        /// </summary>
        internal static string SwipeLeftMid {
            get {
                return ResourceManager.GetString("SwipeLeftMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwipeLeftStartEnd.
        /// </summary>
        internal static string SwipeLeftStartEnd {
            get {
                return ResourceManager.GetString("SwipeLeftStartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwipeRightMid.
        /// </summary>
        internal static string SwipeRightMid {
            get {
                return ResourceManager.GetString("SwipeRightMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwipeRightStartEnd.
        /// </summary>
        internal static string SwipeRightStartEnd {
            get {
                return ResourceManager.GetString("SwipeRightStartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap.
        /// </summary>
        internal static string Tap {
            get {
                return ResourceManager.GetString("Tap", resourceCulture);
            }
        }
    }
}
